### ISSUE TITLE
How to Install this Modul

### ISSUE THREAD

**Issue by Robiv8** [MMRIZE/MMM-anotherNewsFeed#1]
Hallo,
not an issue but how to install this modul?
Thanks Robi

**Comment by eouia** [comment]
```sh
cd <Your MagicMirror Directory>/modules
git clone https://github.com/MMRIZE/MMM-anotherNewsFeed
cd MMM-anotherNewsFeed
npm install
```

**Comment by Robiv8** [comment]
Thanks, that works so far, I just expressed myself incorrectly.
What does the config look like?
Only with this nothing comes:
showImage: true,
censorWords: ["Some", "improper words", "here"],

**Comment by eouia** [comment]
This module is made for some specific person who requested me.  
It was a just clone module of the default newsfeed app. Only displaying picture and filtering word features are added. So all other config is the same with default config app. But, the recent changes are not applied.
